#!/usr/bin/env python3
"""T16 — tabulate the P0 outcomes for the decision gate.

Reads whatever of the P0 evidence exists in <results> and writes docs/gate_summary_v10.md with
each branch condition of PLAN_v10 §3 evaluated numerically as TRUE / FALSE / NOT RUN. Sonnet
tabulates only; every branch outcome is the author's decision.

Blocks: m0_control, detector, feasible_rerun, oracle_select, order9, lookup/recoverability,
paper1_consistency.  Missing inputs are reported as NOT RUN, never guessed.
Usage: python3 scripts/gate_summary_v10.py [--results results_pub] [--legacy results_v8]
"""
from __future__ import annotations
import argparse, json
from pathlib import Path
import numpy as np
from scipy.stats import fisher_exact

ROOT = Path(__file__).resolve().parents[1]
SEEDS = {"": 42, "_s123": 123, "_s777": 777}
TAU = 5.0


def wilson(k, n, z=1.959963984540054):
    if n <= 0:
        return (0.0, 1.0)
    p = k / n; d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, c - h), min(1.0, c + h))


def newcombe(k1, n1, k2, n2):
    """Newcombe hybrid-score 95 % CI for p1 - p2 (independent proportions)."""
    p1, p2 = k1 / n1, k2 / n2
    l1, u1 = wilson(k1, n1); l2, u2 = wilson(k2, n2)
    lo = (p1 - p2) - np.sqrt((p1 - l1) ** 2 + (u2 - p2) ** 2)
    hi = (p1 - p2) + np.sqrt((u1 - p1) ** 2 + (p2 - l2) ** 2)
    return float(p1 - p2), float(lo), float(hi)


def counts(R, tag=""):
    """Pooled (pretender, n_valid) per structure for reliability_{S}{seed}{tag}."""
    out = {}
    for s in "ABC":
        k = n = 0; runs = 0
        for sx in SEEDS:
            f = R / f"reliability_{s}{sx}{tag}_v8.json"
            if not f.exists():
                continue
            d = json.load(open(f)); k += d["tier1a"]["pretender"]; n += d["meta"]["n_valid"]; runs += 1
        out[s] = (k, n, runs)
    return out


def fwd_mae(R, tag=""):
    """Seed-42 forward test MAE per structure -- the seed the controls are paired with."""
    out = {}
    for s in "ABC":
        f = R / f"finetune_{s}{tag}_v8.json"
        if f.exists():
            out[s] = float(json.load(open(f))["final_test_mae_pct"])
    return out


def main(results, legacy):
    R = ROOT / results
    L = []
    L.append("# Decision-gate summary (v10)")
    L.append("")
    L.append(f"> Generated by `scripts/gate_summary_v10.py` from `{results}/`. Every branch condition of")
    L.append("> PLAN_v10 §3 is evaluated numerically; **all branch outcomes are the author's decision** —")
    L.append("> this file only tabulates. Missing inputs are reported as NOT RUN, never guessed.")
    L.append("")
    dec = []                      # (condition, verdict, evidence)

    # ---------------- 0. synthesis conventions (T13)
    L.append("## 0. Synthesis conventions (T13)")
    L.append("")
    conv = {}
    for tag in ("preliminary", "intermediate", "printed", "tmm_mae"):
        f = R / f"synthesis_v8_{tag}.json"
        if f.exists():
            conv[tag] = json.load(open(f))
    if conv:
        L.append("Author-designated convention: **printed** (Paper 1 Table 5 median *r*, `docs/paper1_published_values.md`).")
        L.append("")
        L.append("| convention | r | order | H1a | H1b | H1c |")
        L.append("|---|---|---|---|---|---|")
        for tag, d in conv.items():
            c = d["convention"]; h = d["hypotheses"]
            mono = {k[:3]: ("monotone" if v["monotone"] else "not monotone") for k, v in h.items()}
            L.append(f"| `{tag}` | {', '.join(f'{k} {v:+.2f}' for k, v in c['r'].items())} | {', '.join(c['order'])} | "
                     f"{mono['H1a']} | {mono['H1b']} | {mono['H1c']} |")
        L.append("")
        for k, v in conv.get("printed", conv[sorted(conv)[0]])["convention"]["hypotheses"].items():
            L.append(f"- **{k}** (printed): {v}")
    else:
        L.append("**NOT RUN** — no `synthesis_v8_<tag>.json`.")
    L.append("")

    # ---------------- 1. M0 from-scratch control  (paired: consumes control_analysis_v10.json)
    # The controls share seed 42's targets with the base run, so the comparison is matched
    # design by design; pooling three base seeds against one control seed and applying
    # independent-proportion methods compared unmatched coverage (codex slice 3, 2026-09-12).
    L.append("## 1. M0 from-scratch control (T06) — paired, seed 42")
    L.append("")
    ca = R / "control_analysis_v10.json"
    C = json.load(open(ca))["conditions"] if ca.exists() else {}
    f_tl, f_m0 = fwd_mae(R, ""), fwd_mae(R, "_m0")

    def paired_block(cond, label):
        v = C[cond]; pr, sc = v["primary"], v["secondary"]
        L.append(f"Pooled over {v['n_paired']} paired designs: Hodges–Lehmann shift in Δ (control − base) "
                 f"**{pr['hodges_lehmann']:+.2f} pp** [{pr['hodges_lehmann_ci95'][0]:+.2f}, {pr['hodges_lehmann_ci95'][1]:+.2f}], "
                 f"Wilcoxon p = {pr['wilcoxon_p']:.4f}; pretenders {sc['pretender_base']} → {sc['pretender_control']} "
                 f"(discordant {sc['discordant_base_only']}/{sc['discordant_control_only']}, exact McNemar p = "
                 + (f"{sc['mcnemar_p']:.3f}" if sc["mcnemar_p"] is not None else "n/a") + ").")
        L.append("")
        L.append(f"| structure | base pretenders (seed 42) | {label} pretenders | median shift | HL shift [95 %] | Wilcoxon p | direction |")
        L.append("|---|---|---|---|---|---|---|")
        for r in v["per_structure"]:
            direction = ("control worse" if r["median_paired_shift_pp"] > 0 else "control better") if r["wilcoxon_p"] is not None and r["wilcoxon_p"] < 0.05 else "n.s."
            hl = (f"{r['hodges_lehmann_shift_pp']:+.2f} [{r['hodges_lehmann_ci95_pp'][0]:+.2f}, {r['hodges_lehmann_ci95_pp'][1]:+.2f}]"
                  if r.get("hodges_lehmann_shift_pp") is not None else "–")
            L.append(f"| {r['structure']} | {r['pretender_base']}/{r['n_paired']} | {r['pretender_control']}/{r['n_paired']} | "
                     f"{r['median_paired_shift_pp']:+.2f} pp | {hl} | "
                     + (f"{r['wilcoxon_p']:.4f}" if r["wilcoxon_p"] is not None else "–") + f" | {direction} |")
        L.append("")
        return v

    if "m0" not in C:
        L.append("**NOT RUN** — no paired M0 analysis in `control_analysis_v10.json`.")
        dec += [("M0 forward MAE <= 5 % and the paired HL shift interval lies within ±1 pp of Δ", "NOT RUN", "-"),
                ("TL has significantly more pretenders than M0 (McNemar p < 0.05 with base > control)", "NOT RUN", "-"),
                ("M0 forward MAE > 5 % in any structure", "NOT RUN", "-")]
    else:
        v = paired_block("m0", "M0")
        m0_bad = [s for s in "ABC" if f_m0.get(s, 0) > 5.0]
        L.append("Forward MAE: " + ", ".join(f"{s} TL {f_tl.get(s, float('nan')):.2f} % / M0 {f_m0.get(s, float('nan')):.2f} %" for s in "ABC"))
        L.append("")
        lo, hi = v["primary"]["hodges_lehmann_ci95"]
        within1 = -1.0 < lo and hi < 1.0
        dec.append(("M0 forward MAE <= 5 % in all structures **and** the pooled paired HL-shift interval within ±1 pp",
                    "TRUE" if (not m0_bad and within1) else "FALSE",
                    f"M0 fwd MAE > 5 % in {m0_bad or 'none'}; HL CI [{lo:+.2f}, {hi:+.2f}] within ±1 pp: {within1}"))
        sc = v["secondary"]; mp = sc["mcnemar_p"]
        tl_more = mp is not None and mp < 0.05 and sc["pretender_base"] > sc["pretender_control"]
        dec.append(("TL has significantly more pretenders than M0 (exact McNemar p < 0.05 **and** base > control) with M0 fwd MAE <= 5 %",
                    "TRUE" if (tl_more and not m0_bad) else "FALSE",
                    f"pretenders {sc['pretender_base']} → {sc['pretender_control']}, McNemar p = " + (f"{mp:.3f}" if mp is not None else "n/a")))
        dec.append(("M0 forward MAE > 5 % in any structure (comparison confounded)",
                    "TRUE" if m0_bad else "FALSE", f"structures over 5 %: {m0_bad or 'none'}"))
    L.append("")

    # ---------------- 2. detector benchmark
    L.append("## 2. Surrogate-side detector benchmark (T07)")
    L.append("")
    f = R / "detector_bench_v8.json"
    if not f.exists():
        L.append("**NOT RUN** — no `detector_bench_v8.json`.")
        dec += [("Any pooled ensemble-detector AUROC >= 0.75 with CI excluding 0.5", "NOT RUN", "-"),
                ("All pooled ensemble AUROC CIs include 0.5", "NOT RUN", "-")]
    else:
        db = json.load(open(f))
        L.append("| detector | " + " | ".join(f"{s} AUROC [95 % CI]" for s in "BAC") + " |")
        L.append("|---|---|---|---|")
        strong, ens_all_null = [], True
        for k in db["detectors"]:
            cells = []
            for s in "BAC":
                e = db["pooled"][s][k]
                cells.append(f"{e['auroc']:.2f} [{e['ci_lo']:.2f}, {e['ci_hi']:.2f}]")
                if e["auroc"] >= 0.75 and e["ci_excludes_0p5"]:
                    strong.append((s, k, e["auroc"], e["ci_lo"], e["ci_hi"]))
                if k == "ens_std" and e["ci_excludes_0p5"]:
                    ens_all_null = False
            L.append(f"| {k} | " + " | ".join(cells) + " |")
        L.append("")
        L.append("36 detector × structure intervals are screened here (target-cluster bootstrap); a cell excluding 0.5 is a selection from that screen, not a pointwise confirmation.")
        L.append("")
        L.append(f"Detectors reaching AUROC ≥ 0.75 with a CI excluding 0.5: "
                 + (", ".join(f"**{s}/{k}** {a:.2f} [{lo:.2f}, {hi:.2f}]" for s, k, a, lo, hi in strong) if strong else "none"))
        dec.append(("Any pooled detector AUROC >= 0.75 with CI excluding 0.5 (withdraw the unqualified contribution 5)",
                    "TRUE" if strong else "FALSE", f"{len(strong)} detector×structure cell(s)"))
        dec.append(("All pooled 3-seed-ensemble AUROC CIs include 0.5 (keep the negative claim, scoped)",
                    "TRUE" if ens_all_null else "FALSE", "ens_std CIs vs 0.5"))
    L.append("")

    # ---------------- 3. feasibility-constrained rerun  (paired; relative criteria)
    L.append("## 3. Feasibility-constrained rerun (T09) — paired, seed 42")
    L.append("")
    if "feas" not in C:
        L.append("**NOT RUN** — no paired feasibility analysis in `control_analysis_v10.json`.")
        dec += [("Headline holds under the feasible parametrization (McNemar p >= 0.05 and pretenders remain)", "NOT RUN", "-"),
                ("Feasible parametrization collapses the pretender count (>= 50 % relative reduction with McNemar p < 0.05)", "NOT RUN", "-")]
    else:
        v = paired_block("feas", "feasible")
        sc = v["secondary"]; mp = sc["mcnemar_p"]
        kb, kc = sc["pretender_base"], sc["pretender_control"]
        rel_red = (kb - kc) / kb if kb else float("nan")
        L.append(f"Relative reduction in pretenders under the feasible parametrization: {kb} → {kc} = {100*rel_red:.0f} % "
                 f"(the old absolute rule, 'pooled rate < 25 %', was written against a 53 % base rate and is met trivially at 10 %; "
                 f"the criterion is now relative to the matched base).")
        L.append("")
        holds = (mp is None or mp >= 0.05) and kc > 0
        dec.append(("Headline holds under both parametrizations (exact McNemar p >= 0.05 **and** pretenders remain under the feasible box)",
                    "TRUE" if holds else "FALSE", f"{kb} → {kc}, McNemar p = " + (f"{mp:.3f}" if mp is not None else "n/a")))
        collapse = (mp is not None and mp < 0.05) and rel_red >= 0.5
        dec.append(("Feasible parametrization collapses the pretender count (>= 50 % relative reduction **and** McNemar p < 0.05; headline scoped to the unconstrained box)",
                    "TRUE" if collapse else "FALSE", f"relative reduction {100*rel_red:.0f} %, McNemar p = " + (f"{mp:.3f}" if mp is not None else "n/a")))
    L.append("")

    # ---------------- 4. oracle-select, 5. order-9
    for title, fn, note in (("4. Oracle-in-the-loop recovery (T10)", "oracle_select_v8.json", "best-of-8 by oracle vs by surrogate"),
                            ("5. Order-9 spot check (T11)", "order9_spotcheck_v8.json", "dropped in the pub arm: the reference solver is adaptive-order")):
        L.append(f"## {title}")
        L.append("")
        f = R / fn
        if not f.exists():
            L.append(f"**NOT RUN** — no `{fn}` ({note}).")
        else:
            L.append("```json"); L.append(json.dumps(json.load(open(f)), indent=1)[:1500]); L.append("```")
        L.append("")

    # ---------------- 6. lookup null and recoverability
    L.append("## 6. Lookup null and recoverability (T12)")
    L.append("")
    ln, rc = R / "lookup_null_v8.json", R / "recoverability_v8.json"
    if ln.exists():
        d = json.load(open(ln))["runs"]
        L.append("| run | nearest-neighbour ≤ τ | surrogate-claimed ≤ τ | NN median MAE | claimed median MAE |")
        L.append("|---|---|---|---|---|")
        for k, v in d.items():
            L.append(f"| {k} | {v['nn_le_tau']}/{v['n_targets']} | {v['surrogate_claimed_le_tau']}/{v['n_targets']} | "
                     f"{v['nn_mae_median_pct']:.2f} % | {v['surr_claimed_mae_median_pct']:.2f} % |")
    else:
        L.append("**NOT RUN** — no `lookup_null_v8.json`.")
    if rc.exists():
        d = json.load(open(rc))["runs"]
        L.append("")
        L.append("Surrogate MAE at the *true* geometry (median per run): "
                 + ", ".join(f"{k} {v['surr_mae_at_truth_median_pct']:.2f} %" for k, v in d.items()))
    L.append("")

    # ---------------- 7. Paper-1 consistency
    L.append("## 7. Paper-1 consistency audit (T48)")
    L.append("")
    f = ROOT / "docs/paper1_consistency_v10.md"
    if f.exists():
        t = f.read_text()
        for v in ("MATCHES PRINTED", "AS-SUBMITTED ONLY", "NEITHER"):
            L.append(f"- **{v}**: {t.count('**' + v + '**')} claims")
        L.append("")
        L.append("Full table: `docs/paper1_consistency_v10.md`. The printed *r* triple confirmed by the author is")
        L.append("B 0.96 > A 0.83 > C 0.65 (`docs/paper1_published_values.md`), so the **printed-r branch** of the")
        L.append("gate applies: published-*r* ordering is non-monotone in pretender rate.")
    else:
        L.append("**NOT RUN**")
    L.append("")

    # ---------------- branch table
    L.append("## Branch conditions (PLAN_v10 §3)")
    L.append("")
    L.append("| condition | verdict | evidence |")
    L.append("|---|---|---|")
    for c, v, e in dec:
        L.append(f"| {c} | **{v}** | {e} |")
    # the r-convention branches are settled by the author already
    L.append("| Author confirms printed r = +0.83/+0.96/+0.65 (order B > A > C) | **TRUE** | `docs/paper1_published_values.md`, confirmed 2026-09-06 |")
    L.append("| Author confirms printed r = +0.72/+0.64/+0.44 | **FALSE** | that triple is the superseded 2026-06-19 revision (T48 §5) |")
    L.append("")
    L.append("Sonnet does not choose any branch; the author decides title, claims and framing from this table.")

    out = ROOT / "docs/gate_summary_v10.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out}")
    for c, v, e in dec:
        print(f"  {v:<8} {c[:78]}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="results_v8")
    ap.add_argument("--legacy", default="results_v8")
    a = ap.parse_args(); main(a.results, a.legacy)
