#!/usr/bin/env python3
"""T12(3) — per-design supplementary table (all nine runs) from the JSON/npz artifacts:
structure, seed, target no., dataset index, Surr MAE, RCWA MAE, Delta, status, T1-T4 flags,
surrogate MAE at the true geometry, ||u_best - u_true||, support-violation flag, peak-wavelength
shift and peak-absorptance error (C: TE/TM).  Usage: python3 scripts/make_supp_table_v9.py [--results results_v8]
Writes paper/supplementary_v9.md (T35 folds it into supplementary_v10.md).
"""
import argparse, json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SEEDS = {"": 42, "_s123": 123, "_s777": 777}
TAU = 5.0


def main(results):
    R = ROOT / results
    rec = json.load(open(R / "recoverability_v8.json"))["runs"]
    lines = ["# Supplementary — per-design table (generated by scripts/make_supp_table_v9.py)", "",
             f"Source: `{results}/` (reliability, recoverability JSONs; rcwa npz). τ = {TAU:.0f} %. "
             "status: pretender = Surr ≤ τ & RCWA > τ; confirmed = both ≤ τ; honest-failure = Surr > τ; degenerate = solver failure.", "",
             "| S | seed | # | idx | Surr MAE % | RCWA MAE % | Δ pp | status | T1 | T2 | T3 | T4 | Surr@truth % | ‖u*−u_true‖ | support viol. | peak shift nm | peak ΔA |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    n_rows = n_pret = 0
    for s in "ABC":
        for sx, seed in SEEDS.items():
            rel = json.load(open(R / f"reliability_{s}{sx}_v8.json")); rc = np.load(R / f"rcwa_{s}{sx}_v8.npz", allow_pickle=True)
            rr = rec[f"{s}{sx}"]; ps = rel["per_sample"]; tx = rel["taxonomy"]["per_sample"]
            keys = ("A_TE", "A_TM") if s == "C" else ("A",)
            for i in range(len(ps["orig_indices"])):
                ms, mr = ps["mae_surr_pct"][i], ps["mae_rcwa_pct"][i]
                failed = bool(rc["failed"][i]) or mr is None or not np.isfinite(mr)
                status = "degenerate" if failed else ("pretender" if (ms <= TAU and mr > TAU) else ("confirmed" if (ms <= TAU and mr <= TAU) else "honest-failure"))
                n_rows += not failed; n_pret += status == "pretender"
                shift = "/".join("—" if rr["peaks"][k]["peak_wavelength_shift_nm"][i] is None else f"{rr['peaks'][k]['peak_wavelength_shift_nm'][i]:+.0f}" for k in keys)
                aerr = "/".join("—" if rr["peaks"][k]["peak_absorptance_error"][i] is None else f"{rr['peaks'][k]['peak_absorptance_error'][i]:+.2f}" for k in keys)
                lines.append(f"| {s} | {seed} | {i+1} | {ps['orig_indices'][i]} | {ms:.2f} | {'—' if failed else f'{mr:.2f}'} | "
                             f"{'—' if failed else f'{mr-ms:+.2f}'} | {status} | {int(tx['t1'][i])} | {int(tx['t2'][i])} | {int(tx['t3'][i])} | {int(tx['t4'][i])} | "
                             f"{rr['surr_mae_at_truth_pct'][i]:.2f} | {rr['u_dist_best_true'][i]:.2f} | {int(rr['support_violation_flag'][i])} | {shift} | {aerr} |")
    lines += ["", f"Valid designs: {n_rows}; pretenders: {n_pret}."]
    out = ROOT / "paper" / ("supplementary_v9.md" if results == "results_v8" else f"supplementary_v9_{results}.md")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {n_rows} valid rows, {n_pret} pretenders")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--results", default="results_v8"); main(ap.parse_args().results)
